#!/bin/zsh

# Load sources
source "$SCRIPTDIR/src/load_script_sources" && load_script_sources

### SET VARIABLES ###
	# Parameters
		section="$1"
		upper=$1:u
		file=${SCRIPTDIR}/src/cnf_aliases

### DETERMINE ACTION/SECTION ###
case "$1" in
        cat)
            sed -n 's:.*###\(.*\)###.*:\1:p' ${file}
            ;;
        *)
            sed -n "/### $1:u ###/,/## end/p" ${file}
            ;;

esac


