#!/bin/bash
cd $(dirname "$0");

### INCLUDE SOURCES ###
source "$(dirname "$0")/src/load_sources" && load_sources;

### SET VARIABLES ###

	# Parameters
	     action="$1"
	     path="$2"
	     author="$3"
	     date="$4"

### PARAMETER CHECK ###
if [ "${action}" != "status" ] && [ "${action}" != "pull" ] && [ "${action}" != "changes" ] && [ "${action}" != "log-since" ] && [ "${action}" != "log-on" ]; then
        echo -e " ${ERR} An error occurred: please provide a valid action" && exit;
fi

if [[ ! -d "${path}" ]]; then
        echo -e " ${ERR} An error occurred: please provide a valid directory containing repositories as a parameter" && exit;
fi



### ENTER REPOROOT AND CHECK EACH REPO STATUS
if [[ "${action}" = "status" ]] || [[ "${action}" = "pull" ]]; then

	for D in ${path}/*; do

	    if [[ -d "${D}" && -d "${D}/.git" ]]; then

	        output=$(git --git-dir=${D}/.git --work-tree=${D} ${action});

	        echo -e "${BLCYAN} $(basename ${D}) ${RA}";

		if [[ ${output} == *"Your branch is ahead of"* ]]; then

	        	echo -e "${LGREEN} ${output} ${RA}";

		elif [[ ${output} == *"Your branch is behind"* ]];then

			echo -e "${RED} ${output} ${RA}"

		else

			echo -e "${output}";

		fi

	        ${N};
	    fi
	done

fi
if [[ "${action}" = "changes" ]]; then

        for D in ${path}/*; do
            if [[ -d "${D}" ]]; then
		output=$(git --git-dir=${D}/.git --work-tree=${D} status);
		if [[ ${output} == *"Changes"* ]]; then
			echo -e "${BLCYAN} $(basename ${D}) ${RA}";
			echo -e "${output}";
		fi
            fi

        done

fi

if [[ "${action}" = "log-since" ]]; then

	if [ -z ${date} ]; then
		date=$(date -dlast-monday +%Y-%m-%d);
	fi

        for D in ${path}/*; do
            if [[ -d "${D}" ]]; then
                output=$(git --git-dir=${D}/.git --work-tree=${D} log --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit --after="${date}" --author=${author});
                        echo -e "${BLCYAN} $(basename ${D}) ${RA}";
                        echo -e "${output}";
                        ${N};
            fi
	    ${N}
        done

fi

if [[ "${action}" = "log-on" ]]; then

        if [ -z ${date} ]; then
                date=$(date +%Y-%m-%d);
        fi

        for D in ${path}/*; do
            if [[ -d "${D}" ]]; then
                output=$(git --git-dir=${D}/.git --work-tree=${D} log --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit --after="${date} 00:00" --before="${date} 23:59"  --author=${author});
                        echo -e "${BLCYAN} $(basename ${D}) ${RA}";
                        echo -e "${output}";
                        ${N};
            fi
            ${N}
        done

fi
