#!/bin/zsh

# Load sources
	source "$SCRIPTDIR/src/load_script_sources" && load_script_sources

# Go to the Vagrant folder and launch the container
	cd /home/dries/.Vagrant
	vagrant up

# Launch phpStorm (as seperate process)
	pstorm &

# Show if pulls are required to start working
	gitservice changes /home/dries/Drive/Development/web/repos/dasmedia
	echo -e '${lblue_f} DASMEDIA repositories ${ra}'
	gitservice changes /home/dries/Drive/Development/web/repos/drieshooghe
	echo -e '${lblue_f} DRIESHOOGHE repositories ${ra}'
