#!/bin/zsh

#############################
#          ALIASES          #
#############################


### GENERAL ###

# tools

alias zshconf="vim ~/.zshrc"
alias showpath="echo “${PATH//:/$’\n’}”"
alias ls="ls -l"
alias lsa="ls -al"

## end


### WEB ###

# tools
alias entrDkr='docker exec -it local_web_1 bash'
alias entrVgr="/Users/Dries/.Vagrant/vagrant ssh"

# git
alias ga='git add'
alias gps='git push'
alias gl='git log'
alias gs='git status'
alias gd='git diff'
alias gcm='git commit -m'
alias gb='git branch'
alias gck='git checkout'
alias gra='git remote add'
alias grr='git remote rm'
alias gpl='git pull'
alias gcl='git clone'
alias gta='git tag -a -m'
alias gf='git reflog'
alias gconfdas='git config user.email "dries@dasmedia.be" && git config user.name "Dries Hooghe"'
alias gconfdries='git config user.email "dries.hooghe@gmail.com" && git config user.name "Dries Hooghe"'

## end


### MOBILITY ###

# tools
alias ..="cd .."
alias dep="php vendor/bin/dep"
alias setlarper="sudo chgrp -R www-data storage bootstrap/cache && sudo chmod -R ug+rwx storage bootstrap/cache"

# local ssh

alias entrvgr="cd $HOME/.Vagrant && vagrant ssh"
alias entrdkr="docker exec -it local_web_1 bash"
alias entrmidgard="ssh -p 23023 dries@192.168.0.10"
alias entryggdrasil="ssh -p 23022 dries@192.168.0.11"

# remote ssh

alias travelutgard="ssh dries@82.196.7.87"
alias travelmidgard="ssh -p 23023 dries@141.134.240.78"
alias travelyggdrasil="ssh -p 23022 dries@141.134.240.78"

# web directories

alias cdweb="cd $HOME/Development/web"
alias cdlux="cd $HOME/Development/web/luxauto"
alias cdlardef="cd $HOME/Development/web/laravel-default"
alias cddh="cd $HOME/Development/web/drieshooghe"
alias cdrep="cd $HOME/Development/web/repos"
alias cdrepdas="cd $HOME/Development/web/repos/dasmedia"
alias cdrepdries="cd $HOME/Development/web/repos/drieshooghe"
alias cdeland="cd $HOME/Development/web/eland/crm.eland"

# tool directories

alias cddkr="cd $HOME/.Docker"
alias cddkrc="cd $HOME/.Docker/docker-compose"
alias cdvgr="cd $HOME/.Vagrant"

# script directories

alias cdscripts="cd $HOME/Development/scripts"

# development directories

alias cdconf="cd $HOME/Development/configs"
alias cdlog="cd $HOME/Development/logs"

## end


### SCRIPTS ###

# git
alias gsdas="gitservice status $HOME/Development/web/repos/dasmedia"
alias gsdries="gitservice status $HOME/Development/web/repos/drieshooghe"
alias gsweb="gitservice status $HOME/Development/web"
alias gcdas="gitservice changes $HOME/Development/web/repos/dasmedia"
alias gcdries="gitservice changes /home/dries/Drive/Development/web/repos/drieshooghe"
alias gcweb="gitservice changes $HOME/Development/web"
alias gpdas="gitservice pull $HOME/Development/web/repos/dasmedia"
alias gpdries="gitservice pull $HOME/Development/web/repos/drieshooghe"
alias gpweb="gitservice pull $HOME/Development/web"
alias glodas="gitservice log-on $HOME/Development/web/repos/dasmedia Dries"
alias glodries="gitservice log-on $HOME/Development/web/repos/drieshooghe Dries"
alias gloweb="gitservice log-on $HOME/Development/web Dries"
alias glsdas="gitservice log-since $HOME/Development/web/repos/dasmedia Dries"
alias glsdries="gitservice log-since $HOME/Development/web/repos/drieshooghe Dries"
alias glsweb="gitservice log-since $HOME/Development/web Dries"

## end
