#!/bin/zsh

function whereami {

	location="$(/System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport -I | sed -e "s/^  *SSID: //p" -e d)"

	if [[ ${location} = "telenet-3F495"  ]]; then
		echo "home";
	elif [[ ${location} = "DASmedia-5G"  ]]; then
		echo "dasmedia";
	fi
}
