#!/bin/zsh

load_script_sources () {

echo "";
echo "****************************************************************************";

for f in $SCRIPTDIR/src/_*; do
	
	if source $f; then
		printf "*  Successfully loaded \033[92m ${f#$SCRIPTDIR/src/_} \033[0m";
	else
		printf "*  Error: could not collect \033[31m ${f#$SCRIPTDIR/src/_}\033[0m. Aborting script." && exit;
	fi
	echo "";

done;

echo "****************************************************************************";
echo '';

}
