#!/bin/bash

# For this script to work, the script directory must be added to the path

load_config_sources () {

echo "";

for f in $SCRIPTDIR/src/cnf_*; do
	
	if source $f; then
		printf " Successfully loaded \033[92m ${f#${SCRIPTDIR}/src/cnf_} \033[0m";
	else
		printf " Error: could not collect \033[31m ${f#${SCRIPTDIR}/src/cnf_} \033[0m. Aborting script." && exit;
	fi
	echo "";

done;

sleep 1;
clear;

echo '';

}
