#!/bin/bash

load_script_sources () {

echo "";
echo "****************************************************************************";

for f in $SCRIPTDIR/src/_*; do
	
	if source $f; then
		echo -ne "* \033[0;32m Successfully loaded ${f#$SCRIPTDIR/src/_} ${ra}" &&
		sleep 0.5;
	else
		echo -ne "* \e[31m\xe2\x9c\x97 \e[0m Error: could not collect ${f#$SCRIPTDIR/src/_}. Aborting script." && exit;
	fi
	echo "";

done;

echo "****************************************************************************";
echo '';

}
